
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Booking
{

    public int Id { get; set; }

    public Nullable<int> UserId { get; set; }

    public Nullable<int> VendorId { get; set; }

    public Nullable<int> UserServiceId { get; set; }

    public int VendorServiceId { get; set; }

    public int StatusId { get; set; }

    public System.DateTime BookDate { get; set; }

    public System.DateTime Deadline { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }



    public virtual BookingStatus BookingStatus { get; set; }

    public virtual User User { get; set; }

    public virtual UserService UserService { get; set; }

    public virtual Vendor Vendor { get; set; }

    public virtual VendorService VendorService { get; set; }

}

}
