
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Client
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string OAuthClientID { get; set; }

    public string OAuthClientSecret { get; set; }

    public int StatusId { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

}

}
