
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class DiscountCoupon
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DiscountCoupon()
    {

        this.VendorService = new HashSet<VendorService>();

        this.VendorServicePacket = new HashSet<VendorServicePacket>();

    }


    public int Id { get; set; }

    public int StatusId { get; set; }

    public int CouponTypeId { get; set; }

    public int DiscountTypeId { get; set; }

    public string CouponNumber { get; set; }

    public int Quantity { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> ExpireDate { get; set; }



    public virtual CouponType CouponType { get; set; }

    public virtual DiscountCouponStatus DiscountCouponStatus { get; set; }

    public virtual DiscountType DiscountType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VendorService> VendorService { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VendorServicePacket> VendorServicePacket { get; set; }

}

}
