
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Feedback
{

    public int Id { get; set; }

    public int TypeId { get; set; }

    public int StatusId { get; set; }

    public string Email { get; set; }

    public string Subject { get; set; }

    public string Text { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }



    public virtual FeedbackStatus FeedbackStatus { get; set; }

    public virtual FeedbackType FeedbackType { get; set; }

}

}
