
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Notification
{

    public int Id { get; set; }

    public int TypeId { get; set; }

    public int SenderConsumerTypeId { get; set; }

    public int ReceiverConsumerTypeId { get; set; }

    public int SenderId { get; set; }

    public int ReceiverId { get; set; }

    public int StatusId { get; set; }

    public string AdditionalData { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public Nullable<System.DateTime> UpdateDate { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
