
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class Rating
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int VendorServiceId { get; set; }

    public double Value { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string Description { get; set; }

    public virtual User User { get; set; }

    public virtual VendorService VendorService { get; set; }

}

}
