
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class SmsQueue
{

    public int Id { get; set; }

    public int TypeId { get; set; }

    public int StatusId { get; set; }

    public string Text { get; set; }

    public string Recipient { get; set; }

    public Nullable<System.DateTime> SentDate { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public string Description { get; set; }



    public virtual SmsStatus SmsStatus { get; set; }

    public virtual SmsType SmsType { get; set; }

}

}
