
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class UserSetting
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int LangId { get; set; }

    public string Theme { get; set; }



    public virtual Language Language { get; set; }

    public virtual User User { get; set; }

}

}
