
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class UserVerification
{

    public int Id { get; set; }

    public int UserId { get; set; }

    public int VerificationTypeId { get; set; }

    public string VerificationCode { get; set; }

    public System.DateTime ExpireDate { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public bool IsVerified { get; set; }

    public string Description { get; set; }



    public virtual User User { get; set; }

    public virtual UserVerificationType UserVerificationType { get; set; }

}

}
