
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class UserService
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserService()
    {

        this.Booking = new HashSet<Booking>();

    }


    public int Id { get; set; }

    public int UserId { get; set; }

    public int ServiceId { get; set; }

    public int UserEventId { get; set; }

    public bool Status { get; set; }

    public Nullable<decimal> Budget { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Booking> Booking { get; set; }

    public virtual Service Service { get; set; }

    public virtual User User { get; set; }

    public virtual UserEvent UserEvent { get; set; }

}

}
