
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.Booking = new HashSet<Booking>();

        this.Notification = new HashSet<Notification>();

        this.Notification1 = new HashSet<Notification>();

        this.Rating = new HashSet<Rating>();

        this.RealtimeConnection = new HashSet<RealtimeConnection>();

        this.UserActivation = new HashSet<UserActivation>();

        this.UserClaim = new HashSet<UserClaim>();

        this.UserEvent = new HashSet<UserEvent>();

        this.UserService = new HashSet<UserService>();

        this.UserSetting = new HashSet<UserSetting>();

        this.UserVerification = new HashSet<UserVerification>();

    }


    public int Id { get; set; }

    public int RoleId { get; set; }

    public int TypeId { get; set; }

    public int StatusId { get; set; }

    public Nullable<int> MaritalStatus { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> Birthday { get; set; }

    public System.DateTime RegistrationDate { get; set; }

    public string Phone { get; set; }

    public string Username { get; set; }

    public byte[] Salt { get; set; }

    public byte[] Password { get; set; }

    public int LoginCount { get; set; }

    public System.DateTime LastLoginDate { get; set; }

    public int FailedLoginCount { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public int GenderId { get; set; }

    public Nullable<bool> EmailVerified { get; set; }

    public Nullable<bool> PhoneVerified { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Booking> Booking { get; set; }

    public virtual Gender Gender { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notification> Notification { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Notification> Notification1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rating> Rating { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<RealtimeConnection> RealtimeConnection { get; set; }

    public virtual Role Role { get; set; }

    public virtual UserStatus UserStatus { get; set; }

    public virtual UserType UserType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserActivation> UserActivation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserClaim> UserClaim { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserEvent> UserEvent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserService> UserService { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserSetting> UserSetting { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserVerification> UserVerification { get; set; }

    public virtual Vendor Vendor { get; set; }

}

}
