
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class VendorService
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public VendorService()
    {

        this.Booking = new HashSet<Booking>();

        this.Rating1 = new HashSet<Rating>();

        this.VendorServiceExceptionalEvent = new HashSet<VendorServiceExceptionalEvent>();

    }


    public int Id { get; set; }

    public bool Status { get; set; }

    public string Name { get; set; }

    public Nullable<decimal> PriceMin { get; set; }

    public Nullable<decimal> PriceMax { get; set; }

    public Nullable<int> DailyQuantity { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }

    public int ServicePeriodPriceId { get; set; }

    public Nullable<int> DiscountCouponId { get; set; }

    public int VendorServicePacketId { get; set; }

    public Nullable<System.DateTime> ActivationDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<double> Rating { get; set; }

    public string AddressText { get; set; }

    public string ContactInfo { get; set; }

    public string CoordinateX { get; set; }

    public string CoordinateY { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Booking> Booking { get; set; }

    public virtual DiscountCoupon DiscountCoupon { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Rating> Rating1 { get; set; }

    public virtual ServicePeriodPrice ServicePeriodPrice { get; set; }

    public virtual VendorServicePacket VendorServicePacket { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<VendorServiceExceptionalEvent> VendorServiceExceptionalEvent { get; set; }

}

}
