
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Evanto.DAL.Context
{

using System;
    using System.Collections.Generic;
    
public partial class VendorServiceExceptionalEvent
{

    public int Id { get; set; }

    public int VendorServiceId { get; set; }

    public int EventId { get; set; }

    public string Description { get; set; }

    public Nullable<System.DateTime> CreatedDate { get; set; }



    public virtual EventType EventType { get; set; }

    public virtual VendorService VendorService { get; set; }

}

}
