//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using Evanto.BL.DTOs.Core;
using Evanto.DAL.Context;

namespace Evanto.BL.DTOs.Admin
{

    public class UserAdminDto : IDtoBase
    {
        [Key]
        public int Id { get; set; }

        public int RoleId { get; set; }

        public int UserId { get; set; }


        public int TypeId { get; set; }

        public RoleAdminDto Role { get; set; }

        public UserTypeAdminDto UserType { get; set; }

        public UserStatusDto UserStatus { get; set; }


        public int StatusId { get; set; }

        public int? MaritalStatus { get; set; }


        public string FirstName { get; set; }


        public string LastName { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-dd-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime? Birthday { get; set; }


        public DateTime RegistrationDate { get; set; }


        public string Phone { get; set; }


        public string Username { get; set; }


        public byte[] Salt { get; set; }


        public byte[] Password { get; set; }


        public int LoginCount { get; set; }


        public DateTime LastLoginDate { get; set; }


        public int FailedLoginCount { get; set; }

        public List<SelectListItem> Roles { get; set; }

        public List<SelectListItem> Statuses { get; set; }

        public List<VendorServicePacketByAdminDto> VendorServicePackets { get; set; }

        public List<SelectListItem> Types { get; set; }
        public List<UserActivationAdminDto> UserActivation { get; set; }
        public List<UserVerificationAdminDto> UserVerification { get; set; }

        public List<SelectListItem> Genders { get; set; }

        public string VendorName { get; set; }

        public string Description { get; set; }

        public DateTime? CreatedDate { get; set; }

        public string Image { get; set; }

        public int GenderId { get; set; }
        public bool? EmailVerified { get; set; }
        public bool? PhoneVerified { get; set; }

    }
}