//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:18
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace Evanto.BL.DTOs.Admin
{
    
    public class UserVerificationAdminDto : IDtoBase
    {
    public int Id { get; set; }
      public int UserId { get; set; }
      public int VerificationTypeId { get; set; }
      public string VerificationCode { get; set; }
      public System.DateTime ExpireDate { get; set; }
      public Nullable<System.DateTime> CreatedDate { get; set; }
      public bool IsVerified { get; set; }
      public string Description { get; set; }

      public virtual UserVerificationTypeAdminDto UserVerificationType { get; set; }
  }
}