//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Admin
{
    
    public class VendorServiceByAdminDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public bool Status { get; set; }

         
        public string Name { get; set; }

         
        public decimal? PriceMin { get; set; }

         
        public decimal? PriceMax { get; set; }

         
        public int? DailyQuantity { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public int ServicePeriodPriceId { get; set; }

         
        public int? DiscountCouponId { get; set; }

         
        public int VendorServicePacketId { get; set; }

         
        public DateTime? ActivationDate { get; set; }

         
        public DateTime? EndDate { get; set; }
        
    }
}