//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:00
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.Web.Vendor.Models.DTOs
{
    
    public class PaymentDto
    {
         
        public int Id { get; set; }

         
        public int VendorId { get; set; }

         
        public int StatusId { get; set; }

         
        public decimal Amount { get; set; }

         
        public DateTime PaymentDate { get; set; }

         
        public int PaymentTypeId { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public PaymentStatusDto PaymentStatus { get; set; }

         
        public PaymentTypeDto PaymentType { get; set; }
        
    }
}