//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:27:47
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Core
{
    public class EventTypeDto : IDtoBase
    {
         
        public int Id { get; set; }
        
        public string NameEn { get; set; }
        
        public string NameAz { get; set; }

        public string NameRu { get; set; }

        public bool Status { get; set; }

         
        public string Name { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public List<EventServiceDto> EventServices { get; set; }=new List<EventServiceDto>();

         
        public List<UserEventDto> UserEvents { get; set; } = new List<UserEventDto>();

         
        public List<VendorServiceExceptionalEventDto> VendorServiceExceptionalEvents { get; set; } =new List<VendorServiceExceptionalEventDto>();

        
    }
}