//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:27:46
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace Evanto.BL.DTOs.Core
{
    public partial class EventServiceDto
    {
         
        public int Id { get; set; }

         
        public int EventId { get; set; }

         
        public int ServiceId { get; set; }

         
        public string Description { get; set; }

         
        public bool Status { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public EventTypeDto EventType { get; set; }

         
        public ServiceDto Service { get; set; }

        
    }
}