//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:27:49
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace Evanto.BL.DTOs.Core
{
    public class FeedbackDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public int TypeId { get; set; }

         
        public int StatusId { get; set; }

         
        public string Email { get; set; }

         
        public string Subject { get; set; }

         
        public string Text { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public FeedbackStatusDto FeedbackStatus { get; set; }

         
        public FeedbackTypeDto FeedbackType { get; set; }
        
    }
}