//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:27:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace Evanto.BL.DTOs.Core
{
    public partial class FileDto
    {
        public int Id { get; set; }

        
        public int RelationalId { get; set; }

         
        public int TypeId { get; set; }
        public int? ParentId { get; set; }

         
        public int ContentTypeId { get; set; }

         
        public string Name { get; set; }

         
        public string Extension { get; set; }

         
        public string Path { get; set; }

         
        public string MediaType { get; set; }

         
        public string Description { get; set; }

         
        public bool? Status { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public ContentTypeDto ContentType { get; set; }

         
        public FileTypeDto FileType { get; set; }
        
    }
}