//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:08
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Core
{
    
    public class ServiceDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public bool Status { get; set; }

         
        public string Name { get; set; }

        public string NameEn { get; set; }

        public string NameAz { get; set; }

        public string NameRu { get; set; }

        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public List<EventServiceDto> EventServices { get; set; } = new List<EventServiceDto>();

         
        public List<ServicePeriodPriceDto> ServicePeriodPrices { get; set; } = new List<ServicePeriodPriceDto>();

         
        public List<UserServiceDto> UserServices { get; set; } = new List<UserServiceDto>();
        
    }
}