//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:12
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Core
{
    
    public class UserDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public int RoleId { get; set; }

         
        public int TypeId { get; set; }

         
        public int StatusId { get; set; }

         
        public int? MaritalStatus { get; set; }

         
        public string FirstName { get; set; }

         
        public string LastName { get; set; }

         
        public DateTime? Birthday { get; set; }

         
        public DateTime RegistrationDate { get; set; }

         
        public string Phone { get; set; }

         
        public string Username { get; set; }

         
        public byte[] Salt { get; set; }

         
        public byte[] Password { get; set; }

         
        public int LoginCount { get; set; }

         
        public DateTime LastLoginDate { get; set; }

         
        public int FailedLoginCount { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public int GenderId { get; set; }

         
        public List<BookingDto> Bookings { get; set; } = new List<BookingDto>();

         
        public GenderDto Gender { get; set; }

         
        public RoleDto Role { get; set; }

         
        public UserStatusDto UserStatus { get; set; }

         
        public UserTypeDto UserType { get; set; }

         
        public List<UserActivationDto> UserActivations { get; set; } = new List<UserActivationDto>();

         
        public List<UserClaimDto> UserClaims { get; set; } = new List<UserClaimDto>();

         
        public List<UserEventDto> UserEvents { get; set; } = new List<UserEventDto>();

         
        public List<UserServiceDto> UserServices { get; set; } = new List<UserServiceDto>();

         
        public VendorDto Vendor { get; set; }

        
    }
}