//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Core
{
    
    public class UserServiceDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public int UserId { get; set; }

         
        public int ServiceId { get; set; }

         
        public int UserEventId { get; set; }

         
        public bool Status { get; set; }

         
        public decimal? Budget { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public List<BookingDto> Bookings { get; set; } = new List<BookingDto>();

         
        public ServiceDto Service { get; set; }

         
        public UserDto User { get; set; }

         
        public UserEventDto UserEvent { get; set; }

        
    }
}