//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:21
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Core
{
    
    public class UserEventDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public int UserId { get; set; }

         
        public int EventId { get; set; }

         
        public bool Status { get; set; }

         
        public decimal? Budget { get; set; }

         
        public DateTime EventDate { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public string Name { get; set; }

         
        public EventTypeDto EventType { get; set; }

         
        public UserDto User { get; set; }

         
        public List<UserServiceDto> UserServices { get; set; } = new List<UserServiceDto>();

        
    }
}