//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:36
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace Evanto.BL.DTOs.Core
{
    
    public class VendorServicePacketDto : IDtoBase
    {
         
        public int Id { get; set; }

         
        public int VendorId { get; set; }

         
        public int StatusId { get; set; }

         
        public int? DiscountCouponId { get; set; }

         
        public int PaymentId { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public DateTime? ActivationDate { get; set; }

         
        public DiscountCouponDto DiscountCoupon { get; set; }

         
        public PaymentDto Payment { get; set; }

         
        public VendorDto Vendor { get; set; }

         
        public List<VendorServiceDto> VendorServices { get; set; } = new List<VendorServiceDto>();

         
        public VendorServicePacketStatusDto VendorServicePacketStatus { get; set; }

        
    }
}