//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.3.0.0 (entitiestodtos.codeplex.com).
//     Timestamp: 2017/01/20 - 23:28:35
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------

using System;

namespace Evanto.BL.DTOs.Core
{
    
    public class VendorServiceExceptionalEventDto: IDtoBase
    {
         
        public int Id { get; set; }

         
        public int VendorServiceId { get; set; }

         
        public int EventId { get; set; }

         
        public string Description { get; set; }

         
        public DateTime? CreatedDate { get; set; }

         
        public EventTypeDto EventType { get; set; }

         
        public VendorServiceDto VendorService { get; set; }
        
    }
}