//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evanto.Resources.Operations.User.Create {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateUserResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateUserResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evanto.Resources.Operations.User.Create.CreateUserResource", typeof(CreateUserResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFirstnameMaxlength.
        /// </summary>
        public static string UserFirstnameMaxlength {
            get {
                return ResourceManager.GetString("UserFirstnameMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFirstnameMinlength.
        /// </summary>
        public static string UserFirstnameMinlength {
            get {
                return ResourceManager.GetString("UserFirstnameMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFirstnameRequired.
        /// </summary>
        public static string UserFirstnameRequired {
            get {
                return ResourceManager.GetString("UserFirstnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLastnameMaxlength.
        /// </summary>
        public static string UserLastnameMaxlength {
            get {
                return ResourceManager.GetString("UserLastnameMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLastnameMinlength.
        /// </summary>
        public static string UserLastnameMinlength {
            get {
                return ResourceManager.GetString("UserLastnameMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserLastnameRequired.
        /// </summary>
        public static string UserLastnameRequired {
            get {
                return ResourceManager.GetString("UserLastnameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPasswordMaxlength.
        /// </summary>
        public static string UserPasswordMaxlength {
            get {
                return ResourceManager.GetString("UserPasswordMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPasswordMinlength.
        /// </summary>
        public static string UserPasswordMinlength {
            get {
                return ResourceManager.GetString("UserPasswordMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPasswordRequired.
        /// </summary>
        public static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPhoneMaxlength.
        /// </summary>
        public static string UserPhoneMaxlength {
            get {
                return ResourceManager.GetString("UserPhoneMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPhoneMinlength.
        /// </summary>
        public static string UserPhoneMinlength {
            get {
                return ResourceManager.GetString("UserPhoneMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPhoneRequired.
        /// </summary>
        public static string UserPhoneRequired {
            get {
                return ResourceManager.GetString("UserPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserUsernameMaxlength.
        /// </summary>
        public static string UserUsernameMaxlength {
            get {
                return ResourceManager.GetString("UserUsernameMaxlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserUsernameMinlength.
        /// </summary>
        public static string UserUsernameMinlength {
            get {
                return ResourceManager.GetString("UserUsernameMinlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserUsernameRequired.
        /// </summary>
        public static string UserUsernameRequired {
            get {
                return ResourceManager.GetString("UserUsernameRequired", resourceCulture);
            }
        }
    }
}
